#!/bin/bash
# For some news readers it makes sense to specify the NEWSSERVER variable here
#export NEWSSERVER=your.news.server

export MAN_POSIXLY_CORRECT=1
export EDITOR=vim

export PATH=$HOME/bin:/sbin:/usr/sbin:$PATH

export GPG_TTY=$(tty)

: ${SUDO_ASKPASS:=/usr/lib/ssh/x11-ssh-askpass}
export SUDO_ASKPASS

: ${XAUTHORITY:=$HOME/.Xauthority}
export XAUTHORITY

test $0 != '/bin/sh' || return 0

for rc in $(dirname $(readlink -e $HOME/.bashrc))/*rc; do
    [[ $rc =~ bashrc$ ]] || source $rc
done

